// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrJ5zB1nnar3uRQGSnEjzMwH-V84j-O8',
    appId: '1:575810152008:web:e01c0ff6c0838bb564da7d',
    messagingSenderId: '575810152008',
    projectId: 'relawanin-mobile-project',
    authDomain: 'relawanin-mobile-project.firebaseapp.com',
    databaseURL: 'https://relawanin-mobile-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'relawanin-mobile-project.appspot.com',
    measurementId: 'G-1JM4RX2EJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsNGLYELPjtPelPRrzuV0WxvAfv8OHyA',
    appId: '1:575810152008:android:37c7144b793e4e8664da7d',
    messagingSenderId: '575810152008',
    projectId: 'relawanin-mobile-project',
    databaseURL: 'https://relawanin-mobile-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'relawanin-mobile-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcvMNkjHFmf7xu1OcsF_39M71te-_9VNQ',
    appId: '1:575810152008:ios:12bfbc226f8c780c64da7d',
    messagingSenderId: '575810152008',
    projectId: 'relawanin-mobile-project',
    databaseURL: 'https://relawanin-mobile-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'relawanin-mobile-project.appspot.com',
    iosBundleId: 'com.example.relawaninMobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcvMNkjHFmf7xu1OcsF_39M71te-_9VNQ',
    appId: '1:575810152008:ios:12bfbc226f8c780c64da7d',
    messagingSenderId: '575810152008',
    projectId: 'relawanin-mobile-project',
    databaseURL: 'https://relawanin-mobile-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'relawanin-mobile-project.appspot.com',
    iosBundleId: 'com.example.relawaninMobileProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrJ5zB1nnar3uRQGSnEjzMwH-V84j-O8',
    appId: '1:575810152008:web:5be3cc259f0cdd2464da7d',
    messagingSenderId: '575810152008',
    projectId: 'relawanin-mobile-project',
    authDomain: 'relawanin-mobile-project.firebaseapp.com',
    databaseURL: 'https://relawanin-mobile-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'relawanin-mobile-project.appspot.com',
    measurementId: 'G-VMT60HT2C5',
  );
}
